
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  sources:
    - repoURL: https://charts.softonic.io
      chart: hello-world-app
      targetRevision: 1.2.2
      helm:
        valueFiles:
          - $values/values/client-a/hello-world.yaml
    - repoURL: https://github.com/kanzalqalandri/gitops.git
      targetRevision: main
      ref: values
      path: values/client-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
