apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-api
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: my-api
  # 👇 multi-source: 1) Helm chart, 2) Git values
  sources:
    - chart: my-api                 # your published chart name
      repoURL: oci://ghcr.io/your-org/charts
      targetRevision: 2.1.0         # pin or use a semver range (see below)
    - repoURL: https://github.com/your-org/gitops.git
      targetRevision: main
      ref: values                   # gives us a $values/ path
      path: values/client-a         # folder that has my-api.yaml values
  source:
    helm:
      valueFiles:
        - $values/my-api.yaml       # pulled from the Git values source
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
