apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kanzalqalandri/gitops.git
    targetRevision: main
    path: charts/client-a/storageclass
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
